outfile=filelist.js
echo "// generated by scripts/update_filelist.sh" > $outfile
echo "olapp.exportFiles = [" >> $outfile
find lib -type f -printf "'%p',\n" >> $outfile
find plugins -type f -printf "'%p',\n" >> $outfile
find js -type f -printf "'%p',\n" >> $outfile
find files -type f -printf "'%p',\n" >> $outfile
echo "'olapp.js'," >> $outfile
echo "'olapp.css'" >> $outfile
echo "];" >> $outfile
